### PR TITLE
chore: add node abstraction

### PR DESCRIPTION
**Pull request by kckeiks**
## Why

Passes node service state to other tests after bootstrapping.

## Checklist

- N/A I have made corresponding changes to the tests
- N/A I have made corresponding changes to the documentation
- N/A I have run the app using my feature and ensured that no functionality is broken

### CODE REVIEW

**Comment by matthias-wright** [comment]
Looks great, left a comment

**Comment by kckeiks** [comment]
> Looks great, left a comment

Where is the comment?

**Comment by matthias-wright** [comment]
Weird that it is not visible to you. The node struct has a graphsync store and I was wondering if we should also add a bitswap store.

**Review by matthias-wright — APPROVED** [review]
lgtm

**Pull request merged**
