### PR TITLE
chore(gateway): refactor gateway

### LINKED ISSUE #332: feat(gateway): remove cache from gateway

### PR DESCRIPTION
**Pull request by kckeiks**
## Why

Gateway will not cache content.

Fix #332

## What

- Remove cache.
- Remove admin.
- Remove cache worker.
- Querying indexer, resolving, querying cache node and safe shutdown functionality still work.

## Demo

 

```
cargo run -p ursa-gateway -- daemon
    Finished dev [unoptimized + debuginfo] target(s) in 0.22s
     Running `target/debug/ursa-gateway daemon`
2023-02-07T00:35:37.682950Z  INFO ursa_gateway::config: Load config at: "/Users/acadia/.ursa/gateway/config.toml"
  2023-02-07T00:35:37.703780Z  INFO ursa_gateway::server: Server listening on 0.0.0.0:80
    at crates/ursa-gateway/src/server/mod.rs:131
    in ursa_gateway::Server worker
    in ursa_gateway::Daemon start

  2023-02-07T00:35:39.928627Z  INFO ursa_gateway::resolver: File size received 27044
    at crates/ursa-gateway/src/resolver/mod.rs:122
    in ursa_gateway::server::route::api::v1::get::Get car handler
    in axum_tracing_opentelemetry::middleware::trace_extractor::HTTP request with otel.name: GET /:cid, http.client_ip: , http.flavor: 2.0, http.host: , http.method: GET, http.route: /:cid, http.scheme: https, http.target: /bafybeifyjj2bjhtxmp235vlfeeiy7sz6rzyx3lervfk3ap2nyn4rggqgei, http.user_agent: curl/7.84.0, otel.kind: server, trace_id: 9845efd21d35dad3aa084e3d5203c85c

  2023-02-07T00:35:39.932307Z  INFO tower_http::trace::on_response: finished processing request, latency: 5840 μs, status: 200, response_headers: {"content-type": "application/vnd.curl.car; charset=utf-8", "content-disposition": "attachment; filename=\"bafybeifyjj2bjhtxmp235vlfeeiy7sz6rzyx3lervfk3ap2nyn4rggqgei.car\"", "trace_id": "9845efd21d35dad3aa084e3d5203c85c", "x-request-id": "4a7e5d5c-97dc-446d-b0fb-f9e6aebe6480"}
    at /Users/acadia/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-http-0.3.5/src/trace/on_response.rs:254
    in axum_tracing_opentelemetry::middleware::trace_extractor::HTTP request with otel.name: GET /:cid, http.client_ip: , http.flavor: 2.0, http.host: , http.method: GET, http.route: /:cid, http.scheme: https, http.target: /bafybeifyjj2bjhtxmp235vlfeeiy7sz6rzyx3lervfk3ap2nyn4rggqgei, http.user_agent: curl/7.84.0, otel.kind: server, trace_id: 9845efd21d35dad3aa084e3d5203c85c

^C  2023-02-07T00:35:41.986662Z  INFO ursa_gateway: Gateway shutting down...
    at crates/ursa-gateway/src/main.rs:106
    in ursa_gateway::Daemon start

  2023-02-07T00:35:41.987522Z  INFO ursa_gateway: Server stopped
    at crates/ursa-gateway/src/main.rs:74
    in ursa_gateway::Server worker
    in ursa_gateway::Daemon start

  2023-02-07T00:35:41.987974Z  INFO ursa_gateway: Gateway shut down successfully
    at crates/ursa-gateway/src/main.rs:98
    in ursa_gateway::Daemon start
```

## Checklist

- [x] I have made corresponding changes to the tests
- [x] I have made corresponding changes to the documentation
- [x] I have run the app using my feature and ensured that no functionality is broken

### CODE REVIEW

**Comment by kckeiks** [comment]
No issues found with tracing.
Screenshot 2023-02-07 at 12 13 34 PM

**Comment by scott-dn** [comment]
since there is no cache, we can just simply return the stream without re-streaming again a.k.a stream pipeline.
for example:
> https://github.com/tokio-rs/axum/blob/main/examples/reverse-proxy/src/main.rs#L49

**Comment by kckeiks** [comment]
> since there is no cache, we can just simply return the stream without re-streaming again a.k.a stream pipeline. for example:
> 
> https://github.com/tokio-rs/axum/blob/main/examples/reverse-proxy/src/main.rs#L49

We check for errors in the response so we can try another provider so we can't just pass the resp as shown in the link.
```rust
        for addr in provider_addresses.into_iter() {
            let endpoint = format!("{addr}/ursa/v0/{cid}");
            let uri = match endpoint.parse::<Uri>() {
                Ok(uri) => uri,
                Err(e) => {
                    error!("Error parsed uri: {endpoint} {e:?}");
                    continue;
                }
            };
            match self.client.get(uri).await {
                Ok(resp) => {
                    return Ok(resp);
                }
                Err(e) => error!("Error querying the node provider: {endpoint:?} {e:?}"),
            };
        }
```

**Comment by scott-dn** [comment]
> > since there is no cache, we can just simply return the stream without re-streaming again a.k.a stream pipeline. for example:
> > https://github.com/tokio-rs/axum/blob/main/examples/reverse-proxy/src/main.rs#L49
> 
> We check for errors in the result from `client::get` so we can try another provider so we can't just pass the resp as shown in the link.
> 
> ```rust
>         for addr in provider_addresses.into_iter() {
>             let endpoint = format!("{addr}/ursa/v0/{cid}");
>             let uri = match endpoint.parse::<Uri>() {
>                 Ok(uri) => uri,
>                 Err(e) => {
>                     error!("Error parsed uri: {endpoint} {e:?}");
>                     continue;
>                 }
>             };
>             match self.client.get(uri).await {
>                 Ok(resp) => {
>                     return Ok(resp);
>                 }
>                 Err(e) => error!("Error querying the node provider: {endpoint:?} {e:?}"),
>             };
>         }
> ```

that makes scene.

**Review by scott-dn — APPROVED** [review]

**Pull request merged**
