### PR TITLE
refactor(config): use serde default on each struct directly

### PR DESCRIPTION
**Pull request by ozwaldorf**
## Why

simplifies default value logic for configs. Functionality should be the exact same

## Checklist

- [x] ~~I have made corresponding changes to the tests~~
- [x] ~~I have made corresponding changes to the documentation~~
- [x] I have run the app using my feature and ensured that no functionality is broken

### CODE REVIEW

**Comment by b0xtch** [comment]
I thought we already agreed on which pattern to use?

**Comment by ozwaldorf** [comment]
@b0xtch Didn't realize before that we can just put the serde default attribute directly on the entire struct, previously I thought that it was only available for individual fields. @qti3e brought up that we can use this pattern instead when I asked about it for the ursa-consensus crate's default pattern

**Comment by b0xtch** [comment]
> @b0xtch Didn't realize before that we can just put the serde default attribute directly on the entire struct, previously I thought that it was only available for individual fields. @qti3e brought up that we can use this pattern instead when I asked about it for the ursa-consensus crate's default pattern.
> 
> I also triple checked the functionality is the exact same

I brought it up in this PR https://github.com/fleek-network/ursa/pull/242

**Comment by ozwaldorf** [comment]
Yeah at the time wasn't aware the attribute works on structs directly, the docs only gave examples/details of it used for fields only

**Comment by b0xtch** [comment]
> Yeah at the time wasn't aware the attribute works on structs directly, the docs only gave examples/details of it used for fields only



> Yeah at the time wasn't aware the attribute works on structs directly, the docs only gave examples/details of it used for fields only

But in that PR I explain that, but I remember the decision was to use the function defaults instead as the new pattern.

**Pull request closed without merging**
